name: review-pull-request
on: 
  push:
    branches: [ develop ]
# pull_request:
#    branches: [ main ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: actions/github-script@v6
        with:
          script: |
            const { execSync } = require('child_process')
            const { commits } = context.payload.pull_request
            const rawFiles = execSync(`git diff --name-only HEAD HEAD~${commits}`).toString()
            const files = rawFiles.split('\n').filter(Boolean)

            console.log(files)