name: affichage-message
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  affichage-message-job:
    name: affichage-message job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: run affichage-message.ps1
        shell: pwsh
        run: ./github-actions/github-actions/affichage-message.ps1