name: Hello World
on:
  push: 
    branches: ["develop"]
jobs:
  job1:
    name: Afficher le message bonjour avec shell et powershell
    runs-on: ubuntu-latest
    steps:
      - name: Affichage avec shell
        run: echo "Bonjour ESSARRAJ Fouad avec shell"
      - name : Affichage avec powershell
        shell: pwsh
        run : Write-Host "Bonjour Fouad avec powershell"
  job2:
    name: Afficher le message avec job2
    runs-on: ubuntu-latest
    steps:
      - name : Affichage avec job2
        shell: pwsh
        run : Write-Host "Bonjour Fouad avec job2"