name: code-review with Powershell script
on:
  pull_request
jobs:
  code-review:
    name: code-review job
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # inclure l'history de deux commit
      - name: run script.ps1
        shell: pwsh
        run: ./code-review.ps1 "${{ github.event.pull_request.title }}"