name: Hello World
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  job1:
    name: Afficher le message bonjour
    runs-on: ubuntu-latest
    steps:
      - name: run workflow-commands.ps1
        run: echo "Bonjour ESSARRAJ Fouad"