name: on-pullrequest-approved
on:
    pull_request_review:
        types:
        - submitted
jobs:
    on-pullrequest-approved-job:
        permissions: write-all
        runs-on: ubuntu-latest
        # if: github.event.review.state == 'approved'
        steps:
        - name: add label to issue
          run: echo "add label approved"
          env:
            GH_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}