name: update-readme-file
on:
    push:
      branches: [ "develop" ]
    pull_request:
      branches: [ "develop" ]
jobs:
  update-readme-file-job:
    name: Mise à jour de fichier README.md depuis lab-web.json
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # inclure l'history de deux commit
      - name: run update-readme-file.ps1
        shell: pwsh
        run: ./github-actions/update-readme-file/update-readme-file.ps1
      - name: Commit and push changes
        run: |
          git config --global user.name "ESSARRAJ"
          git config --global user.email "essarraj.fouad@gmail.com"
    
          git add .
          git commit -m "change README.md file to be updated with lab-web.json"
          git push